when:
  branch: master
  event: push

steps:
  - name: test
    image: alpine:latest
    commands:
      - apk add --no-cache bash git ffmpeg gum python3 py3-pip jq bc parallel
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install auto-editor
      - export MXTP_ROOT_DIR=$(pwd)
      - export MXTP_ENV="test"
      - export BASHUNIT_VERBOSE=true
      - chmod +x mxtp.sh
      - bash lib/bashunit tests

  - name: mirror
    image: alpine:latest
    environment:
      GITHUB_SSH_KEY:
        from_secret: GITHUB_SSH_KEY
    commands:
      - apk add --no-cache git openssh-client
      - mkdir -p ~/.ssh
      - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan github.com >> ~/.ssh/known_hosts
      - git remote add github git@github.com:devcarlosmolero/mxtp.git || true
      - git fetch github master || true
      - git push --force --all --no-tags github
