when:
  branch: master
  event: push

steps:
  - name: test
    image: alpine:latest
    commands:
      - apk add --no-cache bash git ffmpeg gum python3 py3-pip jq
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install auto-editor
      - export MXTP_ROOT_DIR=$(pwd)
      - export MXTP_ENV="test"
      - chmod +x mxtp.sh
      - bash lib/bashunit tests
