when:
  branch: master
  event: push

steps:
  - name: test
    image: alpine:latest
    environment:
      MXTP_ROOT_DIR: ${CI_WORKSPACE}
    commands:
      - apk add --no-cache bash git
      - bash lib/bashunit tests/
